version: '3.7'

services:
  app:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION}
        REMOTE_WORKING_DIR: ${REMOTE_WORKING_DIR}
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
    env_file: .env
    networks:
      - app_network
    depends_on:
      - database

  server:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/data/:/var/log/nginx/
    ports:
      - 80:80
    networks:
      - app_network
    depends_on:
      - app

  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge